project_id = "wnxjeldvzjubfgzvvzov"

[functions.parse-syllabus]
verify_jwt = true

[functions.generate-projects]
verify_jwt = true

[functions.data-enrichment-pipeline]
verify_jwt = false

[functions.discover-companies]
verify_jwt = true